/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Operation.def
	public class EntityBaseEntityCall_OperationBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityBaseEntityCall_OperationBase(UInt16 ecpID, Int32 eid) : base(eid, "Operation")
		{
			entityComponentPropertyID = ecpID;
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

	}

	public class EntityCellEntityCall_OperationBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityCellEntityCall_OperationBase(UInt16 ecpID, Int32 eid) : base(eid, "Operation")
		{
			entityComponentPropertyID = ecpID;
			className = "Operation";
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void reqReady(Byte arg1)
		{
			Bundle pBundle = newCall("reqReady", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeUint8(arg1);
			sendCall(null);
		}

	}
	}
